name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vegan_vita_shop_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build --workspace=packages

      - name: Type checking
        run: npm run check-types

      - name: Linting
        run: npm run lint

      - name: Run tests
        run: npm run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vegan_vita_shop_test
          NEXTAUTH_SECRET: test-secret
          JWT_SECRET: test-jwt-secret

      - name: Build applications
        run: npm run build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vegan_vita_shop_test
          NEXTAUTH_SECRET: test-secret
          JWT_SECRET: test-jwt-secret

  e2e-tests:
    runs-on: ubuntu-latest
    needs: lint-and-test
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: vegan_vita_shop_e2e
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build --workspace=packages

      - name: Build applications
        run: npm run build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vegan_vita_shop_e2e
          NEXTAUTH_SECRET: test-secret
          JWT_SECRET: test-jwt-secret

      - name: Setup database
        run: |
          npm run db:push --workspace=packages/database
          npm run db:seed --workspace=packages/database
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vegan_vita_shop_e2e

      - name: Start applications
        run: |
          npm run start --workspace=apps/api &
          npm run start --workspace=apps/web &
          sleep 30
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/vegan_vita_shop_e2e
          NEXTAUTH_SECRET: test-secret
          JWT_SECRET: test-jwt-secret
          PORT: 3001
          NEXTAUTH_URL: http://localhost:3000

      - name: Run E2E tests
        run: npm run test:e2e:headless --workspace=apps/web